<?php
require_once 'Vue/menu.phtml';
?>

<h2>Bienvenue dans la médiathèque</h2>

<p>Suspendisse auctor odio non purus sagittis aliquam. Aliquam tincidunt arcu at fringilla ultrices. Aliquam sed
    efficitur justo. Nunc eu malesuada velit. Aliquam ac eleifend purus, vehicula vestibulum metus. Fusce mattis justo
    enim, quis sollicitudin dui fermentum et. Donec vitae tincidunt dui. Cras scelerisque fringilla magna, in
    scelerisque quam ornare a. Donec aliquam lorem vel diam viverra, vitae convallis lacus tempor. Praesent vulputate
    elit vitae dapibus interdum. Fusce eleifend tortor ut egestas feugiat. Proin nec ligula vel dolor egestas
    interdum.</p>

<p>Sed commodo eu sapien sit amet pharetra. Ut a euismod dui, in gravida nunc. Vestibulum ante ipsum primis in faucibus
    orci luctus et ultrices posuere cubilia curae; Vivamus ut mi eleifend, rutrum augue eget, aliquam nulla. Aliquam
    luctus, velit ut commodo pretium, felis ex iaculis velit, id tincidunt mauris nulla eu est. Proin lectus lectus,
    consectetur in tempor non, dapibus quis sapien. Suspendisse eget arcu ac nulla dictum suscipit nec vitae nunc. Morbi
    dapibus sem at lorem consequat semper. Donec sagittis diam lorem. Suspendisse congue nisl sapien, a bibendum ipsum
    fermentum id. Nunc at hendrerit augue, lobortis pellentesque justo. </p>
