<?php
include 'Vue/menu.phtml';
?>

<h2>La liste des livres</h2>
<ul>

    <?php
    foreach ($livres as $livre) {
        echo "<li>".$livre['id']." "
            .$livre['titre']." "
            .$livre['realisateur']. " "
            . $livre['anneeDeSortie']
            . " <a href='/31_exercice_mediatheque/index.php?entity=Livre&action=delete&id=".$livre['id']."'>supprimer</a>"
            ."</li>";
    }
    ?>
</ul>