<ul>
    <li><a href="/32_mediatheque_twig/index.php">home</a></li>
</ul>

<ul>
    <li><a href="/32_mediatheque_twig/index.php?entity=Film&action=list">liste des films</a></li>
    <li><a href="/32_mediatheque_twig/index.php?entity=Film&action=last">le dernier film</a></li>
    <li><a href="/32_mediatheque_twig/index.php?entity=Film&action=add">ajouter un film</a></li>
</ul>

<ul>
    <li><a href="/32_mediatheque_twig/index.php?entity=Livre&action=list">liste des livre</a></li>
    <li><a href="/32_mediatheque_twig/index.php?entity=Livre&action=last">le dernier livre</a></li>
    <li><a href="/32_mediatheque_twig/index.php?entity=Livre&action=add">ajouter un livre</a></li>
</ul>